In [1]:
print('Hello')

Hello


In [2]:
import numpy as np

In [3]:
import pandas as pd

In [11]:
# https://pypi.org
# 파이썬 라이브러리

In [13]:
print('Hello Python!')

Hello Python!


In [14]:
print("금융빅데이터분석가 '박태원'")

금융빅데이터분석가 '박태원'


In [15]:
print(1)

1


In [18]:
print(123)

123


In [20]:
print([1,2,3])

[1, 2, 3]


In [21]:
name = input('What is your name?')

What is your name?박태원


In [12]:
# 함수를 정의한다(define):def
def add(a,b):
    x=a+b
    return x
y= add(2,3)
print(y)

5


In [22]:
2+3

5

In [23]:
100*2

200

In [26]:
# math 모듈(Math Module)
# 복잡한 연산이 필요한 경우 math 모듈을 사용
import math
math.log(10)

2.302585092994046

In [27]:
from math import *

In [28]:
log(10)

2.302585092994046

In [29]:
pip list

Package                       Version
----------------------------- --------------------
alabaster                     0.7.12
anaconda-client               1.11.0
anaconda-navigator            2.3.1
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
applaunchservices             0.3.0
appnope                       0.1.2
appscript                     1.1.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.11.7
astropy                       5.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.11.1
bi

Note: you may need to restart the kernel to use updated packages.


In [30]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [31]:
import numpy

In [34]:
import numpy as np

In [35]:
import pandas as pd

In [37]:
# import된 라이브러리(패키지) 내용을 살펴보는 경우 
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [38]:
from math import asin

In [42]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [43]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# np.arange(5.0) 의 경우 
# 전달된 stop 매개변수의 값 0.으로 부터 정수가 아닌 실수값임을 추론
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [46]:
# np.arange(2, 6) 의 경우 
# start=2, stop=6 이 주어진 경우
# [2, 6) 에서 2를 시작으로 1 간격으로 떨어진 수들을 array의 형태로 반환
np.arange(2, 6)

array([2, 3, 4, 5])

In [47]:
# 100부터 150까지
np.arange(100,151)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [49]:
# np.arange(2, 5, 2) 의 경우 
# start=2, stop=5, step=2 
# [2, 5) 에서 2을 시작으로 2 간격으로 떨어진 수들을 array의 형태로 반환
np.arange(2, 5, 2)

array([2, 4])

In [50]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [52]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [53]:
1+2

3

In [54]:
print(1 + 2)

3


In [55]:
5-3

2

In [56]:
1+2
5-3

2

In [57]:
5*3

15

In [58]:
6/3

2.0

In [59]:
5**2

25

In [60]:
5**50

88817841970012523233890533447265625

In [61]:
7/2

3.5

In [62]:
# //  : 나눗셈에서 몫만
7//2

3

In [63]:
# % : 나누기 연산 후 몫이 아닌 나머지를 구함
7%2

1

In [64]:
2+3*2

8

In [65]:
10+6/2

13.0

In [66]:
10-(3*3-1)

2

In [67]:
##부등식의 참과 거짓 계산¶True, False
## 파이썬은 참과 거짓을 계산하는 부등식 연산도 가능

In [69]:
3>1

True

In [70]:
3<1 

False

In [71]:
1>2

False

In [72]:
2==2

True

In [73]:
2==3

False

In [74]:
2!=2

False

In [75]:
2!=3

True

In [76]:
2<=3

True

In [77]:
2>=3

False

In [78]:
# 변수명을 할당(지정)하 여 사용하면 편리

In [79]:
a=3
b=5
a+b

8

In [80]:
c=100
b=5
b+c

105

In [81]:
print(b-a)

2


In [82]:
print(a-b)

-2


In [83]:
print(a/b)

0.6


In [84]:
b**10

9765625

In [2]:
pip install opendartreader

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install pykrx

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.5/125.5 kB 12.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB 6.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
